### ISSUE TITLE
Remove http for mirrors that support https

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-web-repo#36]
Now that many servers support https, I propose to go a little further. I propose to remove the http version from the list when a mirror support https.

Example:
```
{
        "country": "China",
        "url": "https://mirrors.zju.edu.cn/manjaro/",
        "protocols": [
            "http",
            "https"
        ]
}
```
become:
```
{
        "country": "China",
        "url": "https://mirrors.zju.edu.cn/manjaro/",
        "protocols": [
            "https"
        ]
}
```
What do you think ? For me, it is logical evolution.

**Comment by fhdk** [comment]
That seems logical.

What happens when the certificate runs out and the owner forgets to renew it?

I think that if an owner explicitly ask for removal of http - OK - but otherwise it is a nice fallback for the user.

Pacman-mirrors already favors https because it reverse sorts the protocols dictionary.

**Comment by fhdk** [comment]
You're right.

I have PR with removal of http from uex.dk
https://github.com/manjaro/manjaro-web-repo/pull/37

Pacman-mirrors offers the fallback of trusting all SSL certs with the conf setting `SSLVerify = False`

**Comment by Huluti** [comment]
@philmmanjaro are you ok with that ?

**Comment by Huluti** [comment]
Done with f3c4f7296356be12e4da7fa513260dec799949f9. It is very hard to keep such a list with such precise criteria.
